### ISSUE TITLE
About Creative Doc.NET

### ISSUE THREAD

**Issue by prepare** [epsitec/code.fitness.blog#1]
Hello @epsitec ,

sorry for asking here (incorrect place).

I've read the latest post (year 2011) of your Creative Docs .NET at http://www.creativedocs.net/blog/.

I  study Maxim's Agg code ( with full C# port)
and use it in my projects (https://github.com/PaintLab/PixelFarm, https://github.com/LayoutFarm/Typography).

---
Do you have a plan to open source "Creative Docs .NET" ?

**Comment by epsitec** [comment]
We have tackled the idea several times, but the effort of putting it wild in the open is too intimidating for now. If you need access to the source code, I can provide it if for you if you want. E-mail me privately (my last name at epsitec dot ch).

**Comment by prepare** [comment]
yes, opening the source has both dark side and bright side.

here,  I encourage you to open source the project for the bright side!.

If you choose a permissive license,
I (and others) can improve it in some areas
eg. 

1. The text/font/ typography features
2. port to modern .net framework (eg. dotnetcore)
3. add hardware rendering features
4. translate from C# to other lang with some auto-tool
   (eg from C# to js/ web-assembly)

---
Thank you for your reply.
If you consider open source it in the future, 
please notify me too!

:)
